### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by nandometzger** [yanyan-li/SmileSplat#1]
Hi,

thank you for this exciting work.

I am a bit puzzled by one passage in the paper.
"... the more important thing is that [Gaussian surfels] are easier for training compared to the covariance matrix, as several robust large **language** models [1] can be leveraged to train this head."

where [1] DSINE paper: Rethinking Inductive Biases for Surface Normal Estimation

could you explain?

**Comment by yanyan-li** [comment]
> Hi,
> 
> thank you for this exciting work.
> 
> I am a bit puzzled by one passage in the paper. "... the more important thing is that [Gaussian surfels] are easier for training compared to the covariance matrix, as several robust large **language** models [1] can be leveraged to train this head."
> 
> where [1] DSINE paper: Rethinking Inductive Biases for Surface Normal Estimation
> 
> could you explain?

Hi, Thanks for your interests in this work.

In our multi-head decoder part, we have a head for per-pixel normal prediction. And we make use of pseudo ground truth normal maps obtained from DSINE to jointly supervise this head.
